## 배달관련 데이터 확인

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 배달 관련 데이터 확인   //    # ./fusion/data/delivery

delivery_shop = pd.read_csv('./data/delivery/배달 상점 데이터.csv', header=None)
delivery_shop.columns = ['상점ID', '업종명', '상점코드', '시도명', '구군명', '읍면동명', '법정동리명', '행정동코드', '행정동 읍면동명', '도로명주소코드', '도로명']

# delivery_loc = pd.read_csv('./data/delivery/배달자 위치정보 데이터.csv')

delivery_time_mean = pd.read_csv('./data/delivery/시간-지역별 배달 소요시간평균.csv', header=None)
delivery_time_mean.columns = ['날짜', '시간', '도', '시구', '평균시간']

delivery_time_order_count = pd.read_csv('./data/delivery/시간-지역별 배달 주문건수.csv', header=None)
delivery_time_order_count.columns = ['날짜', '시간', '도', '시구', '주문건수']

delivery_time_pay_mean = pd.read_csv('./data/delivery/시간-지역별 배달 평균주문금액.csv', header=None)
delivery_time_pay_mean.columns = ['날짜', '시간', '도', '시구', '평균주문금액']

delivery_job_order_count = pd.read_csv('./data/delivery/업종-지역별 배달 주문건수.csv', header=None)
delivery_job_order_count.columns = ['날짜', '업종', '도', '시', '주문건수']

delivery_job_time_mean = pd.read_csv('./data/delivery/업종-지역별 평균배달소요시간.csv', header=None)
delivery_job_time_mean.columns = ['날짜', '업종', '도', '시', '평균시간']

delivery_job_pay_mean = pd.read_csv('./data/delivery/업종-지역별 평균주문금액.csv', header=None)
delivery_job_pay_mean.columns = ['날짜', '업종', '도', '시', '평균주문금액']

delivery_hum = pd.read_csv('./data/delivery/주문지역 인구 특성.csv', header=None)
delivery_hum.columns = ['기준연월', '시군구코드', '시도명', '시군구명', '5세단위구분', '총인구수', '남성인구수', '여성인구수']

In [ ]:
print("배달 상점 데이터") # 상점ID / 업종명 / 상점코드 / 시도명/ 구군명 / 은면동명/ 법정동리명 / 행정동코드 /행정동 읍면동명 / 도로명주소코드 / 도로명 
display(delivery_shop.head())
print("시간-지역별 배달 소요시간평균") # 날짜 / 시간 / 도 / 시구 / 평균시간
display(delivery_time_mean.head())
print("시간-지역별 배달 주문건수") # 날짜 / 시간 / 도 / 시구 / 주문건수
display(delivery_time_order_count.head())
print("시간-지역별 배달 평균주문금액") # 날짜 / 시간 / 도 / 시구 / 평균주문금액
display(delivery_time_pay_mean.head())
print("업종-지역별 배달 주문건수") # 날짜 / 업종 / 도 / 시 / 주문건수
display(delivery_job_order_count.head())
print("업종-지역별 평균배달소요시간") # 날짜 / 업종 / 도 / 시 / 평균시간
display(delivery_job_time_mean.head())
print("업종-지역별 평균주문금액") # 날짜 / 업종 / 도 / 시 / 평균주문금액
display(delivery_job_pay_mean.head())
print("주문지역 인구 특성") # 기준연월 / 시군구코드 / 시도명 / 시군구명 / 5세단위구분 / 총인구수 / 남성인구수 / 여성인구수
display(delivery_hum.head())

# 사고 관련 데이터 확인

In [ ]:
# ./fusion/data/accident
# 전년도도 같이 가져와야 함

accident_kind1 = pd.read_csv('./data/accident/서울시 교통사고 현황 (자동차종류별) 통계.txt', sep="\t")
accident_safe_count = pd.read_csv('./data/accident/서울시 교통안전지수 통계.txt', sep="\t")
accident_safetyproduct = pd.read_csv('./data/accident/서울시 보호장구 착용여부별 교통사고 사상자수 통계.txt', sep="\t")
accident_bike = pd.read_csv('./data/accident/서울시 자전거 교통사고 통계.txt', sep="\t")
accident_kind2 = pd.read_csv('./data/accident/서울시 차량용도별 교통사고 현황 통계.txt', sep="\t")

In [ ]:
print("서울시 교통사고 현황 (자동차종류별) 통계")
display(accident_kind1)
print("서울시 교통안전지수 통계")
display(accident_safe_count)
print("서울시 보호장구 착용여부별 교통사고 사상자수 통계")
display(accident_safetyproduct)
print("서울시 자전거 교통사고 통계")
display(accident_bike)
print("서울시 차량용도별 교통사고 현황 통계")
display(accident_kind2)

# 배달 데이터 전처리 -> 서울 범위 한정

In [72]:
# 배달 상점 데이터 전처리
import pandas as pd

# 데이터 불러오기 
delivery_shop = pd.read_csv('./data/delivery/배달 상점 데이터.csv', header=None)
delivery_shop.columns = ['상점ID', '업종명', '상점코드', '시도명', '구군명', '읍면동명', '법정동리명', '행정동코드', '행정동 읍면동명', '도로명주소코드', '도로명']

# 서울특별시만 걸러내기
delivery_shop_seoul = delivery_shop.groupby('시도명')
# display(delivery_shop_seoul)
df1 = delivery_shop_seoul.get_group('서울특별시')

# 필요없는 컬럼 삭제하기
df1.drop(df1.columns[[0,2,5,6,7,9,10]], axis=1, inplace=True)
display(df1)

# 저장해서 탐색
# df1.to_excel('./data/delivery/배달상점데이터_서울.xlsx')

# 앞으로 나아가야 할 방향 : 업종별로 묶어서, 각 동에 몇 개씩 있는 지를 시각화?

df1 = df1.groupby('행정동 읍면동명')
print(len(df1)) # 행정동 204개 데이터 --> 행정동은 425개임

C:\Users\parkgun\anaconda3\envs\pydatavenv\lib\site-packages\pandas\core\frame.py:4170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

         업종명    시도명  구군명 행정동 읍면동명
1         치킨  서울특별시  강북구      삼양동
3         한식  서울특별시  강북구      송천동
4         치킨  서울특별시  강북구      송천동
5         치킨  서울특별시  강남구     역삼1동
6      패스트푸드  서울특별시  성북구     정릉1동
...      ...    ...  ...      ...
42480    심부름  서울특별시  서초구     방배2동
42717     치킨  서울특별시  양천구     신월4동
42718    심부름  서울특별시  강동구       길동
42719    심부름  서울특별시  강동구       길동
42742    테스트  서울특별시  동작구     사당2동

[2018 rows x 4 columns]

208

In [73]:
# 시간-지역별 배달 소요시간평균
import pandas as pd

# 데이터 불러오기
delivery_time_mean = pd.read_csv('./data/delivery/시간-지역별 배달 소요시간평균.csv', header=None)
delivery_time_mean.columns = ['날짜', '시간', '도', '시구', '평균시간']

# 서울특별시만 걸러내기
delivery_time_mean = delivery_time_mean.groupby('도')
df2 = delivery_time_mean.get_group('서울특별시')


# 시간별 구분하자 -> 날짜 컬럼 삭제
df2.drop(df2.columns[0], axis=1, inplace=True)
display(df2)

# 저장해서 데이터 탐색
df2.to_excel('./data/delivery/시간-지역별 배달 소요시간평균_서울.xlsx')

# 앞으로 나아가야할 방향 : 21개 구밖에 없음 (서울시는 25개, 누락값을 두고 진행할지?)

C:\Users\parkgun\anaconda3\envs\pydatavenv\lib\site-packages\pandas\core\frame.py:4170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

        시간      도    시구   평균시간
6        0  서울특별시   구로구  22.65
7        0  서울특별시   동작구  22.17
8        0  서울특별시  영등포구  20.41
16       1  서울특별시   구로구  28.09
17       1  서울특별시  영등포구  22.19
...     ..    ...   ...    ...
375208  23  서울특별시   도봉구  22.76
375209  23  서울특별시   양천구  24.33
375210  23  서울특별시  영등포구  24.36
375211  23  서울특별시   용산구  33.07
375212  23  서울특별시   은평구  25.85

[67292 rows x 4 columns]

In [74]:
# 시간-지역별 배달 주문건수
import pandas as pd

# 데이터 불러오기
delivery_time_order_count = pd.read_csv('./data/delivery/시간-지역별 배달 주문건수.csv', header=None)
delivery_time_order_count.columns = ['날짜', '시간', '도', '구', '주문건수']

# 서울특별시만 걸러내기
delivery_time_order_count = delivery_time_order_count.groupby('도')
df3 = delivery_time_order_count.get_group('서울특별시')

# 시간별 구분하자 -> 날짜 컬럼 삭제
df3.drop(df3.columns[0], axis=1, inplace=True)
display(df3)

# 몇 개인지 확인하기
df3 = df3.groupby('구')
print(len(df3)) # 22개 출력  / 서울시 구는 25개임 / 누락값은 어떻게 할지?

C:\Users\parkgun\anaconda3\envs\pydatavenv\lib\site-packages\pandas\core\frame.py:4170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

        시간      도     구  주문건수
6        0  서울특별시   구로구    16
7        0  서울특별시   동작구     1
8        0  서울특별시   마포구     3
9        0  서울특별시  영등포구    14
17       1  서울특별시   구로구     6
...     ..    ...   ...   ...
381056  23  서울특별시   도봉구     4
381057  23  서울특별시   양천구     8
381058  23  서울특별시  영등포구    44
381059  23  서울특별시   용산구     1
381060  23  서울특별시   은평구     9

[69733 rows x 4 columns]

22

In [75]:
# 시간-지역별 배달 평균주문금액
import pandas as pd

# 데이터 불러오기
delivery_time_pay_mean = pd.read_csv('./data/delivery/시간-지역별 배달 평균주문금액.csv', header=None)
delivery_time_pay_mean.columns = ['날짜', '시간', '도', '구', '평균주문금액']

# 서울특별시만 걸러내기
delivery_time_pay_mean = delivery_time_pay_mean.groupby('도')
df4 = delivery_time_pay_mean.get_group('서울특별시')

# 시간별 구분하자 -> 날짜 컬럼 삭제
df4.drop(df4.columns[0], axis=1, inplace=True)
display(df4)

# 몇 개인지 확인하기
df4 = df4.groupby('구')
print(len(df4)) # 20개 출력  / 서울시 구는 25개임 / 누락값은 어떻게 할지?

C:\Users\parkgun\anaconda3\envs\pydatavenv\lib\site-packages\pandas\core\frame.py:4170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

        시간      도     구  평균주문금액
6        0  서울특별시   구로구   23679
7        0  서울특별시   동작구   15400
8        0  서울특별시   마포구   21667
9        0  서울특별시  영등포구   20864
17       1  서울특별시   구로구   19667
...     ..    ...   ...     ...
374549  23  서울특별시   도봉구   30600
374550  23  서울특별시   양천구   26557
374551  23  서울특별시  영등포구   18679
374552  23  서울특별시   용산구   20900
374553  23  서울특별시   은평구   24667

[66875 rows x 4 columns]

20

In [76]:
# 업종-지역별 배달 주문건수
import pandas as pd

# 데이터 불러오기
delivery_job_order_count = pd.read_csv('./data/delivery/업종-지역별 배달 주문건수.csv', header=None)
delivery_job_order_count.columns = ['날짜', '업종', '시', '구', '주문건수']

# 서울특별시만 걸러내기
delivery_job_order_count = delivery_job_order_count.groupby('시')
df5 = delivery_job_order_count.get_group('서울특별시')

# 업종별 구분하자 -> 날짜 컬럼 삭제
df5.drop(df5.columns[0], axis=1, inplace=True)
display(df5)

# 몇 개인지 확인하기
df5 = df5.groupby('구')
print(len(df5)) # 22개 출력  / 서울시 구는 25개임 / 누락값은 어떻게 할지?

C:\Users\parkgun\anaconda3\envs\pydatavenv\lib\site-packages\pandas\core\frame.py:4170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

            업종      시     구  주문건수
6          도시락  서울특별시   구로구    12
7          도시락  서울특별시   도봉구     3
14      돈까스/일식  서울특별시   구로구    11
15      돈까스/일식  서울특별시   도봉구     4
16      돈까스/일식  서울특별시  영등포구     5
...        ...    ...   ...   ...
197155      한식  서울특별시   은평구    59
197183       회  서울특별시   구로구    29
197184       회  서울특별시   도봉구     8
197185       회  서울특별시  영등포구     7
197186       회  서울특별시   은평구    52

[34418 rows x 4 columns]

22

In [77]:
# 업종-지역별 평균배달소요시간
import pandas as pd

# 데이터 불러오기
delivery_job_time_mean = pd.read_csv('./data/delivery/업종-지역별 평균배달소요시간.csv', header=None)
delivery_job_time_mean.columns = ['날짜', '업종', '시', '구', '평균시간']

# 서울특별시만 걸러내기
delivery_job_time_mean = delivery_job_time_mean.groupby('시')
df6 = delivery_job_time_mean.get_group('서울특별시')

# 업종별 구분하자 -> 날짜 컬럼 삭제
df6.drop(df6.columns[0], axis=1, inplace=True)
display(df6)

# 몇 개인지 확인하기
df6 = df6.groupby('구')
print(len(df6)) # 21개 출력  / 서울시 구는 25개임 / 누락값은 어떻게 할지?

C:\Users\parkgun\anaconda3\envs\pydatavenv\lib\site-packages\pandas\core\frame.py:4170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

            업종      시     구   평균시간
5          도시락  서울특별시   구로구  16.36
6          도시락  서울특별시   도봉구  20.90
13      돈까스/일식  서울특별시   구로구  24.53
14      돈까스/일식  서울특별시   도봉구  20.02
15      돈까스/일식  서울특별시  영등포구  20.17
...        ...    ...   ...    ...
195949      한식  서울특별시   은평구  31.95
195977       회  서울특별시   구로구  32.48
195978       회  서울특별시   도봉구  29.67
195979       회  서울특별시  영등포구  33.07
195980       회  서울특별시   은평구  30.67

[34074 rows x 4 columns]

21

In [78]:
# 업종-지역별 평균주문금액
import pandas as pd

# 데이터 불러오기
delivery_job_pay_mean = pd.read_csv('./data/delivery/업종-지역별 평균주문금액.csv', header=None)
delivery_job_pay_mean.columns = ['날짜', '업종', '시', '구', '평균주문금액']

# 서울특별시만 걸러내기
delivery_job_pay_mean = delivery_job_pay_mean.groupby('시')
df7 = delivery_job_pay_mean.get_group('서울특별시')

# 업종별 구분하자 -> 날짜 컬럼 삭제
df7.drop(df7.columns[0], axis=1, inplace=True)
display(df7)

# 몇 개인지 확인하기
df7 = df7.groupby('구')
print(len(df7)) # 20개 출력  / 서울시 구는 25개임 / 누락값은 어떻게 할지?

C:\Users\parkgun\anaconda3\envs\pydatavenv\lib\site-packages\pandas\core\frame.py:4170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

            업종      시     구  평균주문금액
6          도시락  서울특별시   구로구   30958
7          도시락  서울특별시   도봉구   31600
14      돈까스/일식  서울특별시   구로구   25591
15      돈까스/일식  서울특별시   도봉구   20375
16      돈까스/일식  서울특별시  영등포구   18750
...        ...    ...   ...     ...
191269      한식  서울특별시   은평구   23913
191297       회  서울특별시   구로구   37332
191298       회  서울특별시   도봉구   29000
191299       회  서울특별시  영등포구   35000
191300       회  서울특별시   은평구   34769

[33178 rows x 4 columns]

20

In [82]:
# 주문지역 인구 특성
import pandas as pd

# 데이터 불러오기
delivery_hum = pd.read_csv('./data/delivery/주문지역 인구 특성.csv', header=None)
delivery_hum.columns = ['기준연월', '시군구코드', '시', '구', '5세단위구분', '총인구수', '남성인구수', '여성인구수']

# 서울특별시만 걸러내기
delivery_hum = delivery_hum.groupby('시')
df8 = delivery_hum.get_group('서울특별시')

# 필요한 컬럼만 남기자 -> 날짜, 시군구코드 삭제
df8.drop(df8.columns[1], axis=1, inplace=True)
# display(df8)

# 몇 개인지 확인하기
# df8 = df8.groupby('구')
# print(len(df8)) # 전체 있는 것 확인 = 25


# 기준연월은 202006으로 가장 최신 / 나이는 20 > 30 > 40 대 순 / 성별은 여자(90퍼) > 남자(82) --> 배달앱 이용 행태 참조

delivery_hum_EDA= df8.groupby('기준연월')
delivery_hum_EDA = delivery_hum_EDA.get_group(202006)

delivery_hum_EDA_20_female = delivery_hum_EDA.groupby('5세단위구분')

display(delivery_hum_EDA)

          기준연월      시    구  5세단위구분   총인구수  남성인구수  여성인구수
125879  202006  서울특별시  종로구    0-4세   3346   1683   1663
125885  202006  서울특별시  종로구    5-9세   4550   2313   2237
125891  202006  서울특별시  종로구  10-14세   5091   2581   2510
125897  202006  서울특별시  종로구  15-19세   6218   3124   3094
125903  202006  서울특별시  종로구  20-24세  10710   5026   5684
...        ...    ...  ...     ...    ...    ...    ...
128999  202006  서울특별시  강동구  80-84세   6748   2749   3999
129005  202006  서울특별시  강동구  85-89세   3364    977   2387
129011  202006  서울특별시  강동구  90-94세   1455    304   1151
129017  202006  서울특별시  강동구  95-99세    379     80    299
129023  202006  서울특별시  강동구    100+    241     62    179

[525 rows x 7 columns]

# 사고 데이터 전처리

In [90]:
# 서울시 교통사고 현황 (자동차종류별) 통계
import pandas as pd

# 데이터 불러오기
accident_kind1 = pd.read_csv('./data/accident/서울시 교통사고 현황 (자동차종류별) 통계.txt', sep="\t", header=1)

# 데이터 확인
accident_kind1.drop(accident_kind1.columns[[3,4,5,6,7,9]], axis=1, inplace=True)
# display(accident_kind1)

# 연도별 합계로 시각화하자 // 기간(연도) -> 자치구(합계) -> 구분(발생건수) -> 이륜차
data_classify = accident_kind1.groupby('구분')
data_classify = data_classify.get_group('발생건수')

data_classify2 = data_classify.groupby('자치구')
data_classify_fianl = data_classify2.get_group('합계')

data_classify_fianl.to_excel('./data/accident/서울시 교통사고 현황 (자동차종류별) 통계_전처리.xlsx')

In [64]:
# 서울시 교통안전지수 통계
import pandas as pd

# 데이터 불러오기
accident_safe_count = pd.read_csv('./data/accident/서울시 교통안전지수 통계.txt', sep="\t")

# 합계 지우기
accident_safe_count.drop(0, axis=0, inplace=True)

# 데이터 저장
accident_safe_count.to_excel('./data/accident/서울시 교통안전지수 통계_전처리.xlsx')

# 데이터 확인 // 구 단위
display(accident_safe_count)

      기간   자치구  교통안전지수
1   2019   종로구   79.77
2   2019    중구   75.09
3   2019   용산구   79.64
4   2019   성동구   79.60
5   2019   광진구   83.22
6   2019  동대문구   74.03
7   2019   중랑구   77.13
8   2019   성북구   81.42
9   2019   강북구   78.66
10  2019   도봉구   81.71
11  2019   노원구   78.94
12  2019   은평구   81.21
13  2019  서대문구   78.58
14  2019   마포구   81.59
15  2019   양천구   79.44
16  2019   강서구   75.36
17  2019   구로구   76.28
18  2019   금천구   79.99
19  2019  영등포구   73.98
20  2019   동작구   79.56
21  2019   관악구   80.75
22  2019   서초구   77.35
23  2019   강남구   71.33
24  2019   송파구   73.37
25  2019   강동구   77.77

In [53]:
# 서울시 보호장구 착용여부별 교통사고 사상자수 통계
import pandas as pd

# 데이터 불러오기 // 구 단위
accident_safetyproduct = pd.read_csv('./data/accident/서울시 보호장구 착용여부별 교통사고 사상자수 통계.txt', sep="\t")

# 필요없는 컬럼 제거
accident_safetyproduct.drop(accident_safetyproduct.columns[[4,5,6,7]], axis=1, inplace=True)
display(accident_safetyproduct)

## 딱봐도 이건 아니다.. // 착용한 사람 사망자수와 부상자수가 더 많음 // 아니 왜 섞어놨지?
accident_safetyproduct.to_excel('./data/accident/서울시 보호장구 착용여부별 교통사고 사상자수 통계_전처리.xlsx')

      기간   자치구    구분      전체 안전모(헬맷) 안전모(헬맷).1 안전모(헬맷).2 안전모(헬맷).3
0     기간   자치구    구분      전체      착용        착용       미착용      착용불명
1     기간   자치구    구분      전체       계    착용률(%)       미착용      착용불명
2   2019    전체  사망자수     250      44        62        27         9
3   2019    전체  부상자수  53,904   6,657      75.8     2,131     2,129
4   2019   종로구  사망자수       6       -         -         3         -
5   2019   종로구  부상자수   1,559     220        88        30        59
6   2019    중구  사망자수       5       -         -         -         -
7   2019    중구  부상자수   1,615     218      90.5        23        53
8   2019   용산구  사망자수      10       2       100         -         -
9   2019   용산구  부상자수   1,614     138      90.2        15       109
10  2019   성동구  사망자수      13       2        50         2         -
11  2019   성동구  부상자수   1,439     286      79.9        72         9
12  2019   광진구  사망자수       3       -         -         -         -
13  2019   광진구  부상자수   1,316     169      72.5        64        55
14  2019  동대문구  사망자수      15       5      71.4         2         2
15  2019  동대문구  부상자수   1,988     352      76.7       107       172
16  2019   중랑구  사망자수      12       2      66.7         1         -
17  2019   중랑구  부상자수   2,122     342      74.8       115       109
18  2019   성북구  사망자수       8       1      33.3         2         -
19  2019   성북구  부상자수   2,007     334      82.7        70        76
20  2019   강북구  사망자수       7       2        50         2         1
21  2019   강북구  부상자수   1,706     270      76.3        84       106
22  2019   도봉구  사망자수       4       -         -         1         1
23  2019   도봉구  부상자수   1,163     155      64.6        85        76
24  2019   노원구  사망자수       8       1       100         -         -
25  2019   노원구  부상자수   2,302     297        67       146        56
26  2019   은평구  사망자수       7       2        50         2         -
27  2019   은평구  부상자수   1,464     177      66.8        88        63
28  2019  서대문구  사망자수      14       3        60         2         -
29  2019  서대문구  부상자수   1,609     186      77.8        53        59
30  2019   마포구  사망자수       7       1        50         1         -
31  2019   마포구  부상자수   2,123     262      81.9        58        56
32  2019   양천구  사망자수      11       1       100         -         -
33  2019   양천구  부상자수   2,085     142      66.7        71       113
34  2019   강서구  사망자수      20       5       100         -         1
35  2019   강서구  부상자수   2,491     235      72.3        90       188
36  2019   구로구  사망자수      13       3        75         1         -
37  2019   구로구  부상자수   2,096     215      67.8       102        87
38  2019   금천구  사망자수       9       -         -         2         -
39  2019   금천구  부상자수   1,353     177      80.8        42        68
40  2019  영등포구  사망자수      11       -         -         1         -
41  2019  영등포구  부상자수   3,451     465      69.9       200        67
42  2019   동작구  사망자수       5       2       100         -         -
43  2019   동작구  부상자수   2,021     293      83.5        58        61
44  2019   관악구  사망자수      10       4       100         -         -
45  2019   관악구  부상자수   1,755     380      86.2        61        25
46  2019   서초구  사망자수      14       3       100         -         1
47  2019   서초구  부상자수   3,530     262      80.6        63        97
48  2019   강남구  사망자수      14       3       100         -         2
49  2019   강남구  부상자수   5,182     444      85.2        77       198
50  2019   송파구  사망자수      13       1        25         3         -
51  2019   송파구  부상자수   4,003     462      65.6       242       152
52  2019   강동구  사망자수      11       1      33.3         2         1
53  2019   강동구  부상자수   1,910     176      60.5       115        15

In [60]:
# 서울시 자전거 교통사고 통계
import pandas as pd

# 데이터 불러오기
accident_bike = pd.read_csv('./data/accident/서울시 자전거 교통사고 통계.txt', sep="\t")

# 합계 지우기
accident_bike.drop(0, axis=0, inplace=True)

# 데이터 확인
display(accident_bike)

# 데이터 저장
accident_bike.to_excel('./data/accident/서울시 자전거 교통사고 통계_전처리.xlsx')

      기간    지역 발생건수 사망자수 부상자수
1   2019   종로구   40    1   40
2   2019    중구   31    -   32
3   2019   용산구   30    -   31
4   2019   성동구  119    1  124
5   2019   광진구  107    -  112
6   2019  동대문구  183    2  196
7   2019   중랑구  152    2  160
8   2019   성북구   83    1   80
9   2019   강북구  100    2  104
10  2019   도봉구  117    -  137
11  2019   노원구  200    -  208
12  2019   은평구  119    1  127
13  2019  서대문구   58    1   60
14  2019   마포구   93    -   96
15  2019   양천구  140    1  140
16  2019   강서구  157    1  168
17  2019   구로구   90    1   79
18  2019   금천구   73    1   84
19  2019  영등포구  304    1  352
20  2019   동작구   93    -  111
21  2019   관악구   63    1   65
22  2019   서초구   72    -   79
23  2019   강남구  103    -  113
24  2019   송파구  427    -  476
25  2019   강동구  137    1  135

In [69]:
# 서울시 차량용도별 교통사고 현황 통계
import pandas as pd

# 데이터 불러오기
accident_kind2 = pd.read_csv('./data/accident/서울시 차량용도별 교통사고 현황 통계.txt', sep="\t")

# 데이터 전처리
# 1. 필요없는 컬럼 제거
accident_kind2.drop(accident_kind2.columns[[3,4,5,6,7,8,9,10,11,12,13,14,15,16,19]], axis=1, inplace=True)

# 2. 필요없는 행 제거
accident_kind2.drop(accident_kind2.index[[0,1,2,3,4]], axis=0, inplace=True)

# 3. 구분 컬럼으로 묶은 뒤, 발생건수만 출력
accident_kind2 = accident_kind2.groupby('구분')
accident_kind2_EDA = accident_kind2.get_group('발생건수')

# 확인
display(accident_kind2_EDA)

# 데이터 저장
accident_kind2_EDA.to_excel('./data/accident/서울시 차량용도별 교통사고 현황 통계_전처리.xlsx')

      기간   자치구    구분  이륜차  자전거
5   2019   종로구  발생건수  138   19
8   2019    중구  발생건수  148   23
11  2019   용산구  발생건수  108   22
14  2019   성동구  발생건수  142   63
17  2019   광진구  발생건수  122   61
20  2019  동대문구  발생건수  265  110
23  2019   중랑구  발생건수  254   99
26  2019   성북구  발생건수  239   37
29  2019   강북구  발생건수  207   57
32  2019   도봉구  발생건수  145   62
35  2019   노원구  발생건수  198  119
38  2019   은평구  발생건수  150   62
41  2019  서대문구  발생건수  150   48
44  2019   마포구  발생건수  174   52
47  2019   양천구  발생건수  141   70
50  2019   강서구  발생건수  230   72
53  2019   구로구  발생건수  171   71
56  2019   금천구  발생건수  127   40
59  2019  영등포구  발생건수  281  189
62  2019   동작구  발생건수  217   53
65  2019   관악구  발생건수  216   43
68  2019   서초구  발생건수  185   46
71  2019   강남구  발생건수  337   60
74  2019   송파구  발생건수  281  218
77  2019   강동구  발생건수  133   70

C:\Users\parkgun\anaconda3\envs\pydatavenv\lib\site-packages\pandas\core\frame.py:4170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

         업종명    시도명  구군명 행정동 읍면동명
1         치킨  서울특별시  강북구      삼양동
3         한식  서울특별시  강북구      송천동
4         치킨  서울특별시  강북구      송천동
5         치킨  서울특별시  강남구     역삼1동
6      패스트푸드  서울특별시  성북구     정릉1동
...      ...    ...  ...      ...
42480    심부름  서울특별시  서초구     방배2동
42717     치킨  서울특별시  양천구     신월4동
42718    심부름  서울특별시  강동구       길동
42719    심부름  서울특별시  강동구       길동
42742    테스트  서울특별시  동작구     사당2동

[2018 rows x 4 columns]