In [6]:
import pandas as pd

# 자 성희를 구출해봅시다.
df = pd.read_csv("./data/성희센서1.csv")
df.drop(['Unnamed: 0'], axis=1, inplace=True)

,factory_line,minutes,time,temperature,humidity,electrical_energy
0,LINE1_PROC1,6:05:01,2020-12-11 18:05,36.5,10.2,22.4000
1,LINE1_PROC1,6:05:02,2020-12-11 18:05,36.6,10.2,22.4000
2,LINE1_PROC1,6:05:03,2020-12-11 18:05,36.7,10.2,22.4000
3,LINE1_PROC1,6:05:04,2020-12-11 18:05,36.8,10.2,22.4000
4,LINE1_PROC1,6:05:05,2020-12-11 18:05,36.9,10.2,22.4000
...,...,...,...,...,...,...
132,LINE1_PROC1,5:50:44,2020-12-15 17:50,24.6,21.0,46.4527
133,LINE1_PROC1,5:50:47,2020-12-15 17:50,24.6,21.0,40.6461
134,LINE1_PROC1,5:50:50,2020-12-15 17:50,24.6,21.0,40.6461
135,LINE1_PROC1,5:50:53,2020-12-15 17:50,23.4,21.0,52.2593
136,LINE1_PROC1,5:50:56,2020-12-15 17:50,24.6,21.0,40.6461

In [7]:
## 모듈설치
import pandas as pd
import matplotlib
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
from matplotlib import font_manager, rc
font_path = "./data/malgun.ttf"   #폰트파일의 위치
font_name = font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font_name)
plt.rcParams['font.family'] = font_name
plt.rc('font', family='Malgun Gothic')
import warnings
warnings.filterwarnings("ignore")

In [ ]:
plt.